### ISSUE TITLE
dimension dismatch problem

### ISSUE THREAD

**Issue by Coldmooon** [HKUDS/FlashST#1]
I run the provided examples:
  ```
  # Evaluate the performance of MTGNN enhanced by FlashST on the PEMS07M dataset
python Run.py -dataset_test PEMS07M -mode eval -model MTGNN

# Pretrain from scratch with MTGNN model, checkpoint will be saved in FlashST-main/SAVE/pretrain/MTGNN(model name)/xxx.pth
python Run.py -mode pretrain -model MTGNN
  ```
  
But both examples encounter errors:
```
  File "/home/liyang/Developer/FlashST/model/PromptNet.py", line 118, in forward
    hidden = torch.cat([time_series_emb] + node_emb + tem_emb, dim=-1).transpose(1, 3)
RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 228 but got size 57 for tensor number 1 in the list.

```

```
  File "/home/liyang/Developer/FlashST/model/PromptNet.py", line 118, in forward
    hidden = torch.cat([time_series_emb] + node_emb + tem_emb, dim=-1).transpose(1, 3)
RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 358 but got size 90 for tensor number 1 in the list.
```

I have prepared the data according to the README.md

**Comment by LZH-YS1998** [comment]
Hello, I reran the code and did not encounter this issue. Could you provide more details about the experiment, or use the following code to check the dimensions of the tensors before concatenation: 
```
print(time_series_emb.shape, node_emb[0].shape, tem_emb[0].shape, tem_emb[1].shape)
```

**Comment by Estol111** [comment]
> print(time_series_emb.shape, node_emb[0].shape, tem_emb[0].shape, tem_emb[1].shape)

Hello, I have the same problem. I find the dimension of node_emb is [7, 1, 23, 32], while the dimension of  time_series_emb and tem_emb is [7, 1, 228, 32]. Could you help me?
![image](https://github.com/user-attachments/assets/6b3abb1e-00bf-4737-acb8-014fa53824c4)
