### ISSUE TITLE
No data.

### ISSUE THREAD

**Issue by HuieL** [HKUDS/FlashST#2]
Where is the data? NO data folder according to the code structure.

**Comment by LZH-YS1998** [comment]
Please refer to the instruction: 3. Run the code:
"First, download "data" folder from [hugging face (data.zip)](https://huggingface.co/datasets/bjdwh/FlashST-DATA/tree/main) or [wisemodel (data.zip)](https://wisemodel.cn/datasets/BJDWH/FlashST-data/file)"

**Comment by HuieL** [comment]
Get it.
